name: Sis Application Review
on: 
  push:
    branches:
      - viktorija/GitHubActions
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check model objects
        uses: actions/checkout@v4

      - name: Jauna kursa pievieno≈°ana
        run: |
         grep "new Kurss" src/main/java/lv/sis/SisApplication.java

      - name: Izvade
        run:
          echo "Jauns kurss ir pievienots"
        if: success()
      
      
