name: Sis Application Review
on: 
  push:
    branches:
      - viktorija/GitHubActions
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check model objects
        uses: actions/checkout@v4

      - name: Vai ir pievienoti kursi
        run: |
           if grep "new MacibuRezultati" src/main/java/lv/sis/SisApplication.java; then
             echo "Kurss/i ir pievienots/i"
           else
             echo "Nav pievienots neviens kurss"
           fi
      
